name: Deploy Docker to PreProd Server

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh ${{ secrets.PREPROD_SSH_USER }}@${{ secrets.PREPROD_SSH_HOST }} -p ${{ secrets.PREPROD_SSH_PORT }} << 'EOF'
          cd  ${{ secrets.PREPROD_DIR }}
          git pull origin main
          docker-compose down
          export TOKEN=${{ secrets.PREPROD_TOKEN }}
          export SERVER=${{ secrets.PREPROD_SERVER }}
          docker-compose up -d --build
        EOF
    
    - name: Cleanup
      run: rm -rf ~/.ssh